### ISSUE TITLE
Can't find selling or can't sell.

### ISSUE THREAD

**Issue by MattiVboiii** [Predator7158/qb-orangejob#2]
Hello, I've added your script in my server and everything (trees, processing) works but I can't get it to sell it anywhere... First off, I can't find the blip on the map (for selling) and the npc is also not there... Can you help?

Screenshot:
![image](https://user-images.githubusercontent.com/57048210/149175152-bcd806e4-9512-4fff-9bfa-c14babac1c6c.png)

**Comment by Predator7158** [comment]
Any Errors??

**Comment by MattiVboiii** [comment]
No. None.

**Comment by Predator7158** [comment]
What's your version of qb-core opd or new

**Comment by MattiVboiii** [comment]
Currently it's an old one as you can see with the HUD but I'm updating it every day with the new scripts. Are there any dependencies that I need? (Newest core or newest script)

**Comment by Predator7158** [comment]
Try changing the export to old version

**Comment by MattiVboiii** [comment]
Which export?

**Comment by Predator7158** [comment]
local QBCore = exports['qb-core']:GetCoreObject()
**Remove this from server and client.lua**

**And Add This**
local QBCore = nil
    Citizen.CreateThread(function()
    while QBCore == nil do 
        TriggerEvent("QBCore:GetObject", function(obj)QBCore = obj end) 
        Citizen.Wait(200) 
    end 
end)

**And add this to resource.lua**

shared_scripts {
    '@qb-core/import.lua',
}
